name             'testcookbook'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures testcookbook'
long_description 'Installs/Configures testcookbook'
version          '0.1.0'
